### ISSUE TITLE
Does not refresing the input fields

### ISSUE THREAD

**Issue by kamranzafar4343** [mrtayyabriaz/todo-list-ReactJS#2]
Whenever a person adds a todo, the garbage text of the previous todo does'nt go away.

>just comment and then we share thoughts in more than 5 comments from you and me
and you accept my 3 comments

**Comment by mrtayyabriaz** [comment]
yeah, let's fix it.

**Comment by mrtayyabriaz** [comment]
Fixed :)
Thanks for noticing an issue in our app. ❤

**Comment by kamranzafar4343** [comment]
Thanks bruh
